FROM node:18.20-alpine3.19

RUN npm install pm2 -g

WORKDIR /app

COPY package*.json ./

RUN yarn install 

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["pm2-runtime", "start", "ecosystem.config.js"] 


