export type TButtonVariants =
  | 'primary'
  | 'secondary'
  | 'danger'
  | 'primary-secondary'
  | 'outline'
  | 'warning'
  | 'success'
  | 'outline-warning'
  | 'bg-white'
  | 'bg-green'
  | 'warning-yellow'
  | 'warning-border'
  | 'outline-primary'
export type TButtonSizes = 'sm' | 'md'
